In [1]:
# 3. Fin^ the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [2]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr.size

12

In [4]:
arr.ndim

2

In [5]:
# 4. Write python code to access the first row of the following array ?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr[0]

array([1, 2, 3, 4])

In [6]:
# 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr[2,[3]]


array([12])

In [7]:
# 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [8]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
np.random.rand(3,3)

array([[0.69278424, 0.651258  , 0.33791508],
       [0.77612406, 0.67404976, 0.66500344],
       [0.21011594, 0.56500086, 0.01692483]])

In [9]:
# 8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
# np.random.rand(3,2) # Generates a 3x2 array of random numbers between 0 and 1
# >>This function genertes random numbers from a uniform distribution over the range '[0,1)'
# >>It returns an array of specified shape where each element is sampled uniformly from the half-open interval '[0,1)'.
# >>It takes dimmension as arguments rather than th mean and standard deviation 

# np.random.randn(3,2)   # Generates a 3x2 array of random numbers from the standard normal distribution
# >> This function generates random numbers from a standard normal distribution (mean 0, standard deviation 1),also known as a Gaussian distribution  or the standard normal distribution
# >> It reurns an array of specified shape where each element is sampled from a standard normal distribution with mean 0 and standard deviation 1


In [14]:
# 9. Write co^e to increase the ^imension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [16]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [24]:
# 11. Consi^er the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

a = np.array( [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b = np.array( [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [25]:
# index wiLe multiplicatio'
a*b


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [30]:
##Matrix multiplication
# a @ b
result = np.matmul(a,b.T)
print(result)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [31]:
##Add both matrics
a + b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [32]:
# Subtract matrix b from a
b -a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
# Divide matrix  b by a 
b / a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

arr = np.array([1,256,655536],dtype = np.int32)
print("Original array")
print(arr)

swapped = arr.byteswap()

# print("original array:",arr)
print("After swap:")
print(swapped)

Original array
[     1    256 655536]
After swap:
[   16777216       65536 -1342174720]


In [ ]:
# 13. What is the significance of the np.linalg.inv function?
# >>The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. 
# >>The significance of this function lies in its applications across various fields of mathematics, science, engineering, and data analysis.


# Numerical Stability: In numerical computations, matrix inversion can sometimes lead to numerical instability, especially for matrices that are ill-conditioned or nearly singular. In such cases, specialized algorithms or regularization techniques may be employed to improve numerical stability
# Regularization: In statistical modeling and machine learning, regularization techniques such as ridge regression involve the use of the inverse of a matrix. Regularization helps to prevent overfitting by penalizing large coefficients, and the inverse is involved in the computation of the regularized coefficients.


In [40]:
arr = np.array([[1,2,3],[4,5,6]])

In [41]:
np.reshape(arr,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
# 15. What is broadcasting in Numpy?
# >>Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined together in element-wise operations
# >>. It simplifies the process of performing arithmetic operations between arrays of different shapes without explicitly reshaping them to match.

>>Here's how broadcasting works:
# >>Dimensions Compatibility: Broadcasting starts by comparing the dimensions of the input arrays element-wise, starting from the trailing dimensions. It checks if the dimensions are compatible or if one of the dimensions is 1
# >>Padding: If the dimensions are compatible or if one of them is 1, NumPy automatically pads the smaller array with copies of itself along the dimensions that are 1, effectively making the arrays compatible for the operation.
# >>Element-wise Operation: Once the arrays are compatible in shape, NumPy performs the element-wise operation as if the arrays were of the same shape.

SyntaxError: unterminated string literal (detected at line 5) (2389457673.py, line 5)

In [43]:
##example of broad casting
prin

array([[1, 2, 3],
       [4, 5, 6]])